//! main.rs
//! ========
//! RT-QTinyECG-ESP32-Rust: Real-Time ECG Detection Firmware
//! Entry point for ESP32 bare-metal Rust firmware.
//!
//! This is the main firmware for the educational ECG detection prototype.
//! It runs entirely on bare-metal ESP32 with no_std (no Rust standard library).
//!
//! # Pipeline (runs every 4ms = 250 Hz):
//! 1. Read ECG analog signal from ADC (GPIO34 / ADC1_CH6)
//! 2. Store raw sample in ring buffer
//! 3. Apply moving average filter to the new sample
//! 4. When ring buffer is full, extract features and run inference
//! 5. If inference returns "abnormal", turn on LED and buzzer (alert)
//! 6. Log one CSV line over UART:
//!    time_ms,adc_value,filtered_value,inference_us,prediction,alert,alert_latency_ms
//!
//! # Hardware Target:
//!   ESP32 DevKit V1 or any generic ESP32 board.
//!   See docs/wiring_esp32_ad8232.md for pin assignments.
//!
//! # HAL Version Notes:
//!   This firmware is written for esp-hal 0.18.x.
//!   If you use a different version, the ADC, timer, or GPIO APIs may differ.
//!   Search for `// HAL-VERSION-NOTE` comments for version-specific sections.
//!   See firmware/esp32-rust/README_FIRMWARE.md for migration notes.
//!
//! # DISCLAIMER:
//!   This firmware is for educational/prototype use only.
//!   NOT a clinical medical device.

// ── no_std / no_main ──────────────────────────────────────────────────────────
// Required for bare-metal embedded Rust:
//   - no_std: don't use the Rust standard library (no OS, no heap by default)
//   - no_main: don't use the normal Rust main() entry point
#![no_std]
#![no_main]

// ── Module declarations ───────────────────────────────────────────────────────
// Each module corresponds to a file in src/
mod ring_buffer;   // Circular buffer for ECG samples
mod filter;        // Moving average and baseline filters
mod inference;     // Threshold + quantized MLP classifier
mod model_weights; // Int8 quantized weights (auto-generated by export_rust_weights.py)
mod adc_reader;    // ADC abstraction for GPIO34
mod alert;         // LED and buzzer control
mod logger;        // CSV UART serial logger

// ── ESP-HAL imports ───────────────────────────────────────────────────────────
// HAL-VERSION-NOTE: esp-hal 0.18.x import style.
// In older versions (<0.15), the import paths were different.
// In newer versions (>0.18), check esp-hal changelog for breaking changes.
use esp_hal::{
    clock::ClockControl,
    delay::Delay,
    gpio::{Io, Level, Output},
    peripherals::Peripherals,
    prelude::*,
    system::SystemControl,
    timer::timg::TimerGroup,
};

// UART for serial logging
// HAL-VERSION-NOTE: In esp-hal 0.18, UART is accessed via uart::Uart.
// In some versions, Uart0 is separate from the default serial.
use esp_hal::uart::{Uart, UartTx, config::Config as UartConfig};

// esp-println for debug! macro (uses UART0 automatically)
use esp_println::println;

// Panic handler (from esp-backtrace crate)
use esp_backtrace as _;

// ── Application Constants ─────────────────────────────────────────────────────
/// Sampling rate in Hz. Must match the Python simulator's SAMPLE_RATE_HZ.
const SAMPLE_RATE_HZ: u32 = 250;

/// Sampling interval in microseconds: 1_000_000 / 250 = 4000 µs = 4 ms
const SAMPLE_INTERVAL_US: u32 = 1_000_000 / SAMPLE_RATE_HZ;

/// Ring buffer size in samples. 128 samples at 250 Hz = 512 ms window.
const RING_BUF_SIZE: usize = 128;

/// Moving average filter window size (number of samples to average)
const FILTER_WINDOW: usize = 8;

/// LED GPIO pin number (GPIO2 = built-in LED on most ESP32 DevKit boards)
const LED_GPIO: u8 = 2;

/// Buzzer GPIO pin number
const BUZZER_GPIO: u8 = 25;

/// ADC input GPIO pin (GPIO34 = ADC1_CH6, input only on ESP32)
/// NOTE: GPIO34-39 on ESP32 are input-only pins (no pullup/pulldown).
const ECG_ADC_GPIO: u8 = 34;

/// Lead-off detect pins from AD8232 (active HIGH = lead off)
const LO_PLUS_GPIO: u8 = 32;
const LO_MINUS_GPIO: u8 = 33;

/// UART baud rate for serial logging
const UART_BAUD: u32 = 115_200;

// ── Entry Point ───────────────────────────────────────────────────────────────
/// Firmware entry point.
///
/// The `#[entry]` macro from `esp-hal` replaces the normal `main()` function
/// and sets up the correct reset vector for the ESP32.
///
/// This function must never return (embedded systems loop forever).
#[entry]
fn main() -> ! {
    // ── 1. Initialize ESP32 peripherals ──────────────────────────────────────
    // `Peripherals::take()` gives us ownership of all hardware peripherals.
    // This is a singleton: you can only call take() once.
    let peripherals = Peripherals::take();

    // Initialize the system clock
    // HAL-VERSION-NOTE: In esp-hal 0.18, SystemControl replaces SystemExt.
    let system = SystemControl::new(peripherals.SYSTEM);

    // Configure clocks to maximum frequency (240 MHz on ESP32)
    let clocks = ClockControl::max(system.clock_control).freeze();

    // Software delay driver (used for sampling timing)
    // HAL-VERSION-NOTE: Delay is created from clocks in 0.18.
    let delay = Delay::new(&clocks);

    // Timer group 0 (used for cycle counting / timestamp)
    // We use TIMG0 for approximate time measurement.
    // HAL-VERSION-NOTE: Timer API changed in 0.18 → TimerGroup::new().
    let timg0 = TimerGroup::new(peripherals.TIMG0, &clocks);
    // Timer0 could be used for interrupt-based sampling in a more advanced version.
    // For this demo, we use a busy-wait delay for simplicity.

    // ── 2. Initialize GPIO ────────────────────────────────────────────────────
    // Create the IO peripheral abstraction
    // HAL-VERSION-NOTE: In 0.18, GPIO is accessed via Io::new().
    let io = Io::new(peripherals.GPIO, peripherals.IO_MUX);

    // LED output (GPIO2 = built-in LED, active HIGH on DevKit V1)
    // HAL-VERSION-NOTE: Output::new() is the 0.18+ API. Older versions used
    // io.pins.gpioN.into_push_pull_output().
    let led_pin = Output::new(io.pins.gpio2, Level::Low);

    // Buzzer output (GPIO25)
    let buzzer_pin = Output::new(io.pins.gpio25, Level::Low);

    // Lead-off detect inputs (AD8232 LO+ and LO-)
    // GPIO32 and GPIO33 are input with internal pull-down
    // (AD8232 LO outputs are active HIGH when leads are off)
    // HAL-VERSION-NOTE: Use Input::new() with Pull::Down in 0.18.
    // In older versions: gpio32.into_pull_down_input()
    // Here we read them via digital input.
    // NOTE: For simplicity in this demo, lead-off detection is handled
    // by checking the ADC value range. Full GPIO lead-off detection
    // requires adapting Input pin reading to your specific esp-hal version.
    // See adc_reader.rs for lead-off detection notes.

    // ── 3. Initialize ADC ─────────────────────────────────────────────────────
    // ADC1 is used for GPIO34 (ADC1_CH6).
    // The AdcReader struct wraps the ADC initialization.
    // HAL-VERSION-NOTE: ADC API differs significantly between versions.
    // See adc_reader.rs and README_FIRMWARE.md for details.
    //
    // ⚠️ HAL-specific: AdcReader::new() needs to be adapted based on
    // the actual esp-hal version you are using. The implementation in
    // adc_reader.rs shows the pattern; you may need to adjust imports.
    let mut adc_reader = adc_reader::AdcReader::new(
        peripherals.ADC1,
        // io.pins.gpio34,  // Uncomment if your HAL version requires the pin
    );

    // ── 4. Initialize UART ────────────────────────────────────────────────────
    // Use UART0 (connected to USB-UART bridge on DevKit V1)
    // for CSV serial logging.
    // HAL-VERSION-NOTE: Uart::new_with_config() in 0.18.
    // In older versions: Uart::new() or Serial::new().
    //
    // For simplicity, we use esp-println's println! macro for UART output.
    // esp-println routes through UART0 automatically.
    // This avoids needing to wire up Uart manually in this demo.
    println!("RT-QTinyECG-ESP32-Rust Firmware Starting...");
    println!("Sample rate: {} Hz, Buffer: {} samples", SAMPLE_RATE_HZ, RING_BUF_SIZE);
    println!("time_ms,adc_value,filtered_value,inference_us,prediction,alert,alert_latency_ms");

    // ── 5. Initialize application modules ────────────────────────────────────
    // Circular ring buffer for ECG samples
    let mut ring_buf: ring_buffer::RingBuffer<i32, RING_BUF_SIZE> =
        ring_buffer::RingBuffer::new();

    // Alert state machine (LED + buzzer)
    let mut alert_ctrl = alert::AlertController::new(led_pin, buzzer_pin);

    // Filter state (moving average state)
    let mut filter_state = filter::MovingAverageState::<FILTER_WINDOW>::new();

    // ── 6. Main sampling loop ─────────────────────────────────────────────────
    // This loop runs forever at approximately SAMPLE_RATE_HZ.
    // Each iteration:
    //   a) Wait for the sampling interval
    //   b) Read ADC
    //   c) Filter
    //   d) Push to ring buffer
    //   e) Inference (when buffer full)
    //   f) Alert
    //   g) Log

    // Timestamp counter in milliseconds (approximate).
    // We increment this by SAMPLE_INTERVAL_US / 1000 per sample.
    // For a real design, use a hardware timer for accurate timestamps.
    let mut time_ms: u32 = 0;

    // Alert latency state
    // We measure time from "first abnormal detection" to "alert GPIO toggle".
    // On this firmware, the GPIO toggle happens in the same loop iteration,
    // so the latency is approximately the GPIO write time (~few µs).
    let mut alert_start_ms: u32 = 0;
    let mut alert_was_off: bool = true;

    loop {
        // ── a) Fixed sampling interval (busy-wait) ────────────────────────────
        // HAL-VERSION-NOTE: delay.delay_micros() in 0.18.
        // Older versions may use delay.delay_us() or ets_delay_us().
        //
        // For better real-time accuracy, replace this with a timer ISR.
        // Busy-wait accumulates jitter from inference + GPIO time.
        delay.delay_micros(SAMPLE_INTERVAL_US);

        // ── b) Read ADC value ─────────────────────────────────────────────────
        // Returns a 12-bit value: 0–4095 (corresponding to 0–3.3V on ESP32).
        // Returns 0 if leads are off (as reported by lead-off detection).
        let adc_raw: u16 = adc_reader.read_ecg_adc();

        // ── c) Apply moving average filter ────────────────────────────────────
        // Causal filter: only uses past samples, no future look-ahead.
        // This matches the real-time constraint.
        let filtered: i32 = filter_state.push_and_average(adc_raw as i32);

        // ── d) Push filtered value into ring buffer ───────────────────────────
        ring_buf.push(filtered);

        // Default output values (used if buffer not yet full)
        let mut inference_us: u32 = 0;
        let mut prediction:    u8  = 0;    // 0=Normal, 1=Abnormal
        let mut alert_active:  bool = false;
        let mut alert_latency_ms: u32 = 0;

        // ── e) Inference: only when buffer is full ────────────────────────────
        if ring_buf.is_full() {
            // Get a view of the current window
            let window: &[i32] = ring_buf.as_slice();

            // Measure inference time using a simple cycle counter.
            // HAL-VERSION-NOTE: For accurate cycle counting on ESP32, use
            // the CCOUNT register (Xtensa) or a hardware timer.
            // Here we use a simple timestamp approximation.
            //
            // On ESP32 at 240 MHz, 1 µs ≈ 240 cycles.
            // We use esp_hal's timer or a ccount-based approach.
            // For simplicity in this demo, we time using the delay API
            // as a rough approximation. In production, use CCOUNT register.
            //
            // CCOUNT reading (Xtensa-specific, inline assembly):
            // let start_cycles: u32 = unsafe { read_ccount() };
            let t_inference_start_us = 0u32; // Placeholder: replace with real timer

            // Run the ECG inference
            // Inference mode is selected in inference.rs.
            // Default: threshold classifier (no weights needed).
            // Optional: quantized MLP (uses model_weights.rs).
            prediction = inference::infer(window);

            // Estimate inference time (placeholder: use real timer in production)
            // For a real measurement, use CCOUNT (see inference.rs comments).
            // On this demo, we estimate: threshold inference ≈ 5–50 µs.
            inference_us = estimate_inference_us_placeholder();

            // ── f) Alert logic ────────────────────────────────────────────────
            alert_active = prediction == 1;

            if alert_active {
                // Measure latency: time from first detection to alert activation
                if alert_was_off {
                    alert_start_ms   = time_ms;
                    alert_was_off    = false;
                }
                // Alert latency = time from detection to GPIO toggle
                // In this firmware: same iteration → ~0 ms + GPIO overhead (~2 µs)
                alert_latency_ms = time_ms.saturating_sub(alert_start_ms);
                alert_ctrl.alert_on();
            } else {
                alert_ctrl.alert_off();
                alert_was_off = true;
                alert_latency_ms = 0;
            }
        }

        // ── g) Log CSV line over UART ─────────────────────────────────────────
        // CSV format:
        //   time_ms,adc_value,filtered_value,inference_us,prediction,alert,alert_latency_ms
        //
        // We use esp-println's println! which maps to UART0 at 115200 baud.
        // In production, replace with a non-blocking UART write.
        logger::log_csv(
            time_ms,
            adc_raw as i32,
            filtered,
            inference_us,
            prediction,
            alert_active as u8,
            alert_latency_ms,
        );

        // ── Advance timestamp ─────────────────────────────────────────────────
        // Increment by nominal sample interval (4 ms).
        // In a real implementation, read from a hardware timer.
        time_ms = time_ms.wrapping_add(SAMPLE_INTERVAL_US / 1000);
    }
}

// ─── Helper: Placeholder inference time estimator ────────────────────────────
/// Returns a fixed placeholder inference time in microseconds.
///
/// In production, replace this with a real CCOUNT-based measurement:
///
/// ```rust
/// // Xtensa CCOUNT register (cycle counter)
/// // At 240 MHz, each cycle = 1/240 µs ≈ 4.17 ns
/// fn read_ccount() -> u32 {
///     let count: u32;
///     unsafe { core::arch::asm!("rsr.ccount {0}", out(reg) count) };
///     count
/// }
///
/// let start = read_ccount();
/// // ... run inference ...
/// let end = read_ccount();
/// let elapsed_cycles = end.wrapping_sub(start);
/// let elapsed_us = elapsed_cycles / 240; // at 240 MHz
/// ```
///
/// For this educational demo, we return a realistic estimate.
#[inline]
fn estimate_inference_us_placeholder() -> u32 {
    // Threshold inference on ESP32 at 240 MHz is approximately 5–20 µs.
    // MLP inference (5→8→1, int8) is approximately 10–60 µs.
    // This placeholder value should be replaced with real measurement.
    25  // µs (typical for threshold classifier)
}
