//! model_weights.rs
//! ==================
//! Quantized int8 weights and int32 biases for the ECG MLP classifier.
//!
//! Architecture: 5 inputs → 8 hidden (ReLU) → 1 output (threshold)
//!   - Layer 1: W1 shape [8, 5] (8 neurons, 5 inputs each)
//!              b1 shape [8]
//!   - Layer 2: W2 shape [1, 8] (1 output, 8 inputs)
//!              b2 shape [1]
//!
//! Quantization:
//!   Symmetric per-layer: scale_i = max(|W_i|) / 127.0
//!   W_q = clip(round(W / scale), -128, 127)  → stored as i8
//!   b_q = clip(round(b / (scale * input_scale)), ...)  → stored as i32
//!
//! To replace these weights with trained values:
//!   1. Run: python python/generate_dummy_ecg.py
//!   2. Run: python python/train_simple_model.py
//!   3. Run: python python/quantize_weights.py
//!   4. Run: python python/export_rust_weights.py
//!   This file will be automatically regenerated.
//!
//! Used by: src/inference.rs  (mlp_infer() function)
//!
//! DISCLAIMER: These are educational placeholder/trained weights.
//! NOT for clinical medical use.

#![allow(dead_code)]

// ── Model Architecture Constants ──────────────────────────────────────────────

/// Number of input features
pub const N_FEATURES: usize = 5;

/// Number of hidden neurons in Layer 1
pub const N_HIDDEN: usize = 8;

/// Number of output neurons
pub const N_OUTPUT: usize = 1;

// ── TRAINED QUANTIZED WEIGHTS (generated by export_rust_weights.py) ─────────

/// Layer 1 weights W1 [5 x 8], row-major
pub const W1: [i8; 40] = [
    // Layer 1 weights W1 [5 x 8], row-major
     -56,   61,   83,   51,  -20,  -20,  -67,  105,
     -11,   16,  -67,  120,  113,  -10,  -44,  -29,
     -70,  -21,   29,   -6,   67,  -22,  -23,   11,
     -34,   33,  -51,   14,   71,  -44,   37,  -36,
    -115,   60,  127,   91,    8,  -31,   52,   24,
];

/// Layer 1 biases b1 [8]
pub const B1: [i32; 8] = [
    // Layer 1 biases b1 [8]
         -39,      -28,      -57,       93,
         -14,      -15,      -53,        8,
];

/// Layer 2 weights W2 [8 x 1], row-major
pub const W2: [i8; 8] = [
    // Layer 2 weights W2 [8 x 1], row-major
     -36,  -39,  127,   75,  126,   40,    8,   78,
];

/// Layer 2 bias b2 [1]
pub const B2: [i32; 1] = [
    // Layer 2 bias b2 [1]
        -128,
];

/// Layer 1 weight dequantization scale
pub const W1_SCALE: f32 = 0.00712235;
/// Layer 1 bias dequantization scale
pub const B1_SCALE: f32 = 0.00712235;
/// Layer 2 weight dequantization scale
pub const W2_SCALE: f32 = 0.00924780;
/// Layer 2 bias dequantization scale
pub const B2_SCALE: f32 = 0.00924780;
