//! model_weights.rs
//! ==================
//! Quantized int8 weights, int32 biases, and feature normalization constants
//! for the ECG MLP classifier.
//!
//! Architecture: 5 inputs -> 8 hidden (ReLU) -> 1 output (threshold)
//!   - Layer 1: W1 shape [N_HIDDEN x N_FEATURES] = [8 x 5], row-major
//!              B1 shape [N_HIDDEN] = [8]
//!   - Layer 2: W2 shape [N_OUTPUT x N_HIDDEN] = [1 x 8], row-major
//!              B2 shape [N_OUTPUT] = [1]
//!
//! Feature Normalization (CRITICAL for correctness):
//!   Raw features = [mean, max, min, peak_to_peak, centered_energy/4096]
//!   Normalized   = (raw - FEAT_MEAN) / FEAT_STD   (z-score)
//!   FEAT_MEAN and FEAT_STD are computed on the training set by StandardScaler
//!   in train_simple_model.py and exported here.
//!   The firmware MUST apply this normalization before MLP inference.
//!
//! Quantization:
//!   Symmetric per-layer: scale_i = max(|W_i|) / 127.0
//!   W_q = clip(round(W / scale), -128, 127)  -> stored as i8
//!   b_q = clip(round(b / (scale * 127.0)), ...)  -> stored as i32
//!
//! NOTE: This file is a direct port of firmware/esp32-rust/src/model_weights.rs
//! and must remain identical to that file for correct local↔firmware parity.
//!
//! DISCLAIMER: These are educational placeholder/trained weights.
//! NOT for clinical medical use.

#![allow(dead_code)]

// -- Model Architecture Constants --

/// Number of input features
pub const N_FEATURES: usize = 5;

/// Number of hidden neurons in Layer 1
pub const N_HIDDEN: usize = 8;

/// Number of output neurons
pub const N_OUTPUT: usize = 1;

// -- TRAINED QUANTIZED WEIGHTS (generated by export_rust_weights.py) --

/// Layer 1 weights W1 [8 x 5], row-major (each row = one neuron)
pub const W1: [i8; 40] = [
    // Layer 1 weights W1 [8 x 5], row-major (each row = one neuron)
      -8,   14,  -13,    3,  -32,
      -7,   12,  -35,   95,  113,
     127,  -58,  -16,  -45,   83,
      44,   71,   11,   -2,  -11,
      22,   76,   47,   59,   -5,
      -1,   -1,   -8,  -16,    1,
    -121,  -46,  -58,   16,   11,
      78,   -7,   10,  -12,   -2,
];

/// Layer 1 biases B1 [8]
pub const B1: [i32; 8] = [
    // Layer 1 biases B1 [8]
          -1,        2,        2,        1,
           0,        0,        0,        2,
];

/// Layer 2 weights W2 [1 x 8], row-major
pub const W2: [i8; 8] = [
    // Layer 2 weights W2 [1 x 8], row-major
      -2,  -37,  127,   37,   62,   11,  -33,   63,
];

/// Layer 2 bias B2 [1]
pub const B2: [i32; 1] = [
    // Layer 2 bias B2 [1]
          -1,
];

// -- Feature Normalization Constants (from StandardScaler in train_simple_model.py) --
/// Per-feature training mean for z-score normalization.
/// Apply: norm = (raw - FEAT_MEAN) / FEAT_STD before MLP inference.
pub const FEAT_MEAN: [f32; 5] = [2231.946289, 2574.434082, 2125.616455, 448.817688, 2.773446];

/// Per-feature training std for z-score normalization.
pub const FEAT_STD: [f32; 5] = [136.578064, 240.825134, 125.261551, 198.136459, 2.237785];
