//! model_weights.rs
//! ==================
//! Quantized int8 weights, int32 biases, and feature normalization constants
//! for the ECG MLP classifier.
//!
//! Architecture: 5 inputs -> 8 hidden (ReLU) -> 1 output (threshold)
//!   - Layer 1: W1 shape [N_HIDDEN x N_FEATURES] = [8 x 5], row-major
//!              B1 shape [N_HIDDEN] = [8]
//!   - Layer 2: W2 shape [N_OUTPUT x N_HIDDEN] = [1 x 8], row-major
//!              B2 shape [N_OUTPUT] = [1]
//!
//! Feature Normalization (CRITICAL for correctness):
//!   Raw features = [mean, max, min, peak_to_peak, centered_energy/4096]
//!   Normalized   = (raw - FEAT_MEAN) / FEAT_STD   (z-score)
//!   FEAT_MEAN and FEAT_STD are computed on the training set by StandardScaler
//!   in train_simple_model.py and exported here.
//!   The firmware MUST apply this normalization before MLP inference.
//!   This preserves amplitude information across windows (unlike per-window
//!   normalization which destroys it).
//!
//! Quantization:
//!   Symmetric per-layer: scale_i = max(|W_i|) / 127.0
//!   W_q = clip(round(W / scale), -128, 127)  -> stored as i8
//!   b_q = clip(round(b / (scale * 127.0)), ...)  -> stored as i32
//!         Note: input_scale = 127.0 because firmware inputs are clipped to [-128, 127]
//!         after z-score normalization (see mlp_infer() in inference.rs).
//!
//! To replace these weights with trained values:
//!   1. Run: python python/generate_dummy_ecg.py
//!   2. Run: python python/train_simple_model.py
//!   3. Run: python python/quantize_weights.py
//!   4. Run: python python/export_rust_weights.py
//!   This file will be automatically regenerated.
//!
//! Used by: src/inference.rs  (mlp_infer() function)
//!
//! DISCLAIMER: These are educational placeholder/trained weights.
//! NOT for clinical medical use.

#![allow(dead_code)]

// -- Model Architecture Constants --

/// Number of input features
pub const N_FEATURES: usize = 5;

/// Number of hidden neurons in Layer 1
pub const N_HIDDEN: usize = 8;

/// Number of output neurons
pub const N_OUTPUT: usize = 1;

// -- TRAINED QUANTIZED WEIGHTS (generated by export_rust_weights.py) --

/// Layer 1 weights W1 [8 x 5], row-major (each row = one neuron)
pub const W1: [i8; 40] = [
    // Layer 1 weights W1 [8 x 5], row-major (each row = one neuron)
       0,    0,    0,    0,    0,
      66,   45,   18,   56,   -8,
       0,    0,    0,    0,    0,
      12,   49,  -47,  -13,  127,
     -49,   38,    8,   -2,   24,
      -1,   -1,   -1,    0,    0,
       0,    0,    0,    0,    0,
      14,  -12,   -2,    0,    0,
];

/// Layer 1 biases B1 [8]
pub const B1: [i32; 8] = [
    // Layer 1 biases B1 [8]
         -54,       15,      -67,       41,
         -45,       21,      -27,        1,
];

/// Layer 2 weights W2 [1 x 8], row-major
pub const W2: [i8; 8] = [
    // Layer 2 weights W2 [1 x 8], row-major
       0,  -86,    0,  127,   47,    0,    0,    0,
];

/// Layer 2 bias B2 [1]
pub const B2: [i32; 1] = [
    // Layer 2 bias B2 [1]
        -140,
];

// -- Feature Normalization Constants (from StandardScaler in train_simple_model.py) --
/// Per-feature training mean for z-score normalization. Apply: norm = (raw - FEAT_MEAN) / FEAT_STD before MLP inference.
pub const FEAT_MEAN: [f32; 5] = [2231.946289, 2574.434082, 2125.616455, 448.817688, 2.773446];

/// Per-feature training std for z-score normalization.
pub const FEAT_STD: [f32; 5] = [136.578064, 240.825134, 125.261551, 198.136459, 2.237785];
